INSERT INTO products (description, measurement, unitprice, category, type, stock) VALUES ('DESMONTAJE Y MONTAJE DE DEFLECTOR', 'HORAS', 120.00, 'SERVICIO', 'PINTURA', 10);
INSERT INTO products (description, measurement, unitprice, category, type, stock) VALUES ('DESPLAZAMIENTO DEL PERSONAL PARA SERVICIO DE CAMPO (Hr)', 'HORAS', 30.00, 'SERVICIO', 'PINTURA', 10);
INSERT INTO products (description, measurement, unitprice, category, type, stock) VALUES ('MOVILIDAD DEL PERSONAL PARA EL RETORNO', 'HORAS', 7.50, 'SERVICIO', 'PINTURA', 10);
INSERT INTO products (description, measurement, unitprice, category, type, stock) VALUES ('ACELERADOR', 'UNIDAD', 33.99, 'INSUMOS', 'PINTURA', 10);
INSERT INTO products (description, measurement, unitprice, category, type, stock) VALUES ('ANTISILICONE/ ANTICRATER', 'UNIDAD', 59.99, 'INSUMOS', 'PINTURA', 10);
INSERT INTO products (description, measurement, unitprice, category, type, stock) VALUES ('BARNIZ / PLUS HS', 'UNIDAD', 19.99, 'INSUMOS', 'PINTURA', 10);
INSERT INTO products (description, measurement, unitprice, category, type, stock) VALUES ('BASE ACRILICO', 'UNIDAD', 64.99, 'INSUMOS', 'PINTURA', 10);
INSERT INTO products (description, measurement, unitprice, category, type, stock) VALUES ('BASE URETANO PRIMER', 'UNIDAD', 35.99, 'INSUMOS', 'PINTURA', 10);
INSERT INTO products (description, measurement, unitprice, category, type, stock) VALUES ('CATALIZADOR / P25', 'UNIDAD', 49.99, 'INSUMOS', 'PINTURA', 10);
INSERT INTO products (description, measurement, unitprice, category, type, stock) VALUES ('CINTA 3/4"', 'UNIDAD', 59.99, 'INSUMOS', 'PINTURA', 10);
INSERT INTO products (description, measurement, unitprice, category, type, stock) VALUES ('CINTA DOBLE CONTACTO', 'UNIDAD', 99.99, 'INSUMOS', 'PINTURA', 10);
INSERT INTO products (description, measurement, unitprice, category, type, stock) VALUES ('COMBI', 'UNIDAD', 19.99, 'INSUMOS', 'PINTURA', 10);
INSERT INTO products (description, measurement, unitprice, category, type, stock) VALUES ('COLADOR', 'UNIDAD', 29.99, 'INSUMOS', 'PINTURA', 10);
INSERT INTO products (description, measurement, unitprice, category, type, stock) VALUES ('DESENGRASANTE', 'UNIDAD', 49.99, 'INSUMOS', 'PINTURA', 10);
INSERT INTO products (description, measurement, unitprice, category, type, stock) VALUES ('PAPEL 60 CM', 'UNIDAD', 39.99, 'INSUMOS', 'PINTURA', 10);
INSERT INTO products (description, measurement, unitprice, category, type, stock) VALUES ('PULIDOR A  MANO  /PULIDOR 1/4', 'UNIDAD', 69.99, 'INSUMOS', 'PINTURA', 10);
INSERT INTO products (description, measurement, unitprice, category, type, stock) VALUES ('PULIDOR A  MAQUINA / PULIDOR 3M', 'UNIDAD', 59.99, 'INSUMOS', 'PINTURA', 10);
INSERT INTO products (description, measurement, unitprice, category, type, stock) VALUES ('SELLADORA DE PLASTICO', 'UNIDAD', 35.99, 'INSUMOS', 'PINTURA', 10);
INSERT INTO products (description, measurement, unitprice, category, type, stock) VALUES ('THINER ACRILICO', 'UNIDAD', 4.99, 'INSUMOS', 'PINTURA', 10);
INSERT INTO products (description, measurement, unitprice, category, type, stock) VALUES ('THINER EXTRA', 'UNIDAD', 6.99, 'INSUMOS', 'PINTURA', 10);
INSERT INTO products (description, measurement, unitprice, category, type, stock) VALUES ('THINER REDUCER/URETANO', 'UNIDAD', 3.99, 'INSUMOS', 'PINTURA', 10);
INSERT INTO products (description, measurement, unitprice, category, type, stock) VALUES ('TRAPO x KILO', 'UNIDAD', 7.99, 'INSUMOS', 'PINTURA', 10);
INSERT INTO products (description, measurement, unitprice, category, type, stock) VALUES ('WAIPE x KILO', 'UNIDAD', 8.99, 'INSUMOS', 'PINTURA', 10);
INSERT INTO products (description, measurement, unitprice, category, type, stock) VALUES ('WASH PRIMER', 'UNIDAD', 17.99, 'INSUMOS', 'PINTURA', 10);