USE heroku_85749be25763217;
source Tables/customers.sql
source Tables/employees.sql
source Tables/invoicedetails.sql
source Tables/invoices.sql
source Tables/orderdetails.sql
source Tables/orderemployee.sql
source Tables/orders.sql
source Tables/products.sql
source Tables/quotations.sql
source Tables/quotedetails.sql
source Tables/servicesupplie.sql
source Tables/settings.sql
source Tables/users.sql
source Views/servicesupplieview.sql
source Views/vieworder.sql
source Views/vieworderdetail.sql
source Views/viewquote.sql
source Views/viewquotedetail.sql
source Scripts/insert_customers.sql
source Scripts/insert_employees.sql
source Scripts/insert_products.sql
source Scripts/insert_servicesupplie.sql
source Scripts/insert_settings.sql
source Scripts/insert_users.sql